[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
base_mainnet = "${BASE_MAINNET_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"

[etherscan]
base_mainnet = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }
